### ISSUE TITLE
Queation about the "02-Genome_annotations.tar.gz"

### ISSUE THREAD

**Issue by SeaUrchin11** [ChemaMD/OweniaGenome#1]
Dear, 
    Several files in the "02-Genome_annotations.tar.gz" can not be opened. it may fail to upload. Can you upload  a complete file?

**Comment by ChemaMD** [comment]
Hi, what are the exact files? I can send a direct link otherwise

**Comment by SeaUrchin11** [comment]
Thanks for your reply. I need the files including "Capitella_teleta_functional_annotation.xls". I am honored and grateful for your support.

**Comment by ChemaMD** [comment]
Sure, it might be that is a xls file and excel doesn't like it. Here is a link to the xlsx version: https://www.dropbox.com/s/0gk4i6iptgtftxi/Capitella_annotation_v050321_TrinoPanther.xlsx?dl=0

Let me know if it works.

**Comment by SeaUrchin11** [comment]
This website seems impossible to open. If possible, can you send the file directly to this email (qcwang@yic.ac.cn). Thank you for your effort.
